name: 'Leviton Z-Wave Dimmer'
packageKey: 'leviton-zwave-dimmer'
permissions:
  zwave: {}
description: "Customized SmartThings driver for Leviton Z-Wave dimmer devices"
vendorSupportInformation: "https://community.smartthings.com/t/st-edge-driver-for-leviton-z-wave-plus-dimmers-dz6hd-dz1kd/257938"
